# Generated by Django 2.2.1 on 2020-02-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_article_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
