# Generated by Django 2.2.1 on 2020-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200213_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('money', models.IntegerField(verbose_name='价钱')),
                ('pub', models.ForeignKey(on_delete=True, to='app01.Publish')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
