# Generated by Django 2.2.1 on 2020-02-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sheller', '0008_goods_goods_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=36, unique=True, verbose_name='订单编号')),
                ('order_data', models.DateField(auto_now=True, verbose_name='时间')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '拒收'), (6, '已完成')], verbose_name='订单状态')),
                ('order_total', models.FloatField(verbose_name='点单总金额')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sheller.regUser', verbose_name='买家')),
            ],
            options={
                'db_table': 'pay_order',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('goods_total_price', models.IntegerField(verbose_name='订单总金额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sheller.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sheller.regUser', verbose_name='卖家')),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
    ]
