# Generated by Django 2.2.1 on 2020-03-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sheller', '0008_goods_goods_desc'),
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goods_total', models.FloatField(verbose_name='商品价格')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sheller.regUser', verbose_name='买家')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sheller.Goods')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
