# Generated by Django 2.2.1 on 2020-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_useradress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useradress',
            table='user_adress',
        ),
    ]
