# Generated by Django 2.2.1 on 2020-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20200306_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradress',
            name='adress_status',
            field=models.IntegerField(default=1, verbose_name='当前地址状态'),
        ),
    ]
