# Generated by Django 2.2.1 on 2020-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheller', '0002_reguser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
