# Generated by Django 2.2.1 on 2020-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheller', '0003_reguser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
    ]
