# Generated by Django 2.2.1 on 2020-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheller', '0007_auto_20200226_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_desc',
            field=models.TextField(default='very good food', verbose_name='商品描述'),
        ),
    ]
