# Generated by Django 2.2.1 on 2020-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheller', '0008_goods_goods_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'code_info',
            },
        ),
    ]
